name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_HTML: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true

  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node-version: [12, 14]
        os: [windows-2019, ubuntu-18.04, ubuntu-20.04]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run test suite
        run: |
          npm ci
          npm run test --if-present
  
  deploy-test:
    name: Deploy to test env
    runs-on: ubuntu-latest
    needs: [lint, ci]
    environment:
      name: test-env
      url: ${{ env.TARGET_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Determine target url
        id: determine_url
        run: ...
      
      - name: Deploy to test env
        if: ${{ success() }}
        run: |
          echo "Deploying to test environment - ${{ env.TARGET_URL }}..."
          echo "This step would be replaced with e.g. a Marketplace Action for deploying to some target test env..."
      
      - name: Download artifact
        if: ${{ success() }}
        uses: actions/download-artifact@v2
      